### ISSUE TITLE
Correct way to use Vault secret in EDA server

### ISSUE THREAD

**Issue by AGirin** [ansible/eda-server#1271]
Hello,

I am not clear on how to use Vaut password in rulebook? 

I have vault secret created for AWS secret_key... My rule book look like this:

```
- name: AWS SQS
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: <aws_region>
        access_key: '<aws access key>'
        secret_key: '{{ secret_key }}'
        name: test
        delay_seconds: 20

  rules:
    - name: EvenrtBridge schedule to SQS
      condition: event.body.env is defined
      action:
        run_job_template:
          name: test_teplate
          organization: test_org

```

I think I need to use Variables section in Rulebook activation.. But I am not sure how to reference Vault password in Variables and then in rulebook...

Does workflow look like this?

Create Vault password --> use Variable to define new variable for Rulebook Activation --> use this variable in Rulebook...

So, second and third parts are not clear to me...

Thanks,

Andrew

**Comment by mkanoor** [comment]
@AGirin You need to create a new Credential Type in EDA (Automate Decisions -> Infrastructure -> Credential Types and add a type for Amazon SQS.


Inputs Configuration
```
fields:
 - id: queue_name
   type: string
   label: Queue Name
   help_text: Name of your SQS Queue
 - id: queue_url
   type: string
   label: Queue URL
   help_text: URL of your SQS Queue
 - id: access_key
   type: string
   label: Access Key
   secret: true
   help_text: EC2 Access Key
 - id: secret_key
   type: string
   label: Secret Key
   secret: true
   help_text: EC2 Secret Key
 - id: region
   type: string
   label: Region
   help_text: The EC2 Region
required:
   - queue_name
   - queue_url
   - access_key
   - secret_key
   - region
```

Injector Configuration:
```
extra_vars:
   region: '{{region}}'
   queue_url: '{{queue_url}}'
   queue_name: '{{queue_name}}'
   access_key: '{{access_key}}'
   secret_key: '{{secret_key}}'
```

Once you have the type add a Credential (e.g MY_SQS_CRED) of this new type


Create an Activation  and setup the rulebook to look something like [this](https://github.com/mkanoor/eda-project/blob/main/rulebooks/sqs_log_all.yml) then add the MY_SQS_CRED to Activation
